language: minimal

cache:
  directories:
    - packer_cache

sudo: required

addons:
  apt:
    update: true
    packages:
      - kpartx
      - qemu-user-static
      - salt-minion
      - go-dep

install:
  - wget https://github.com/solo-io/packer-builder-arm-image/archive/master.zip -O builder.zip
  - unzip builder.zip
  - wget https://releases.hashicorp.com/packer/1.3.2/packer_1.3.2_linux_amd64.zip -O packer.zip
  - unzip packer.zip -d packer-builder-arm-image-master

script:
  - cd packer-builder-arm-image-master
  - sudo ./packer build ../pnk.json
