version: '3'
services:
  wordpress:
    image: arm32v7/wordpress:5
    container_name: wordpress
    depends_on:
      - wordpress-db
    restart: unless-stopped
    networks:
      - local
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=wordpress-db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - |
        WORDPRESS_CONFIG_EXTRA=
        define('WP_SITE_URL', 'http://pnk');
        define('WP_HOME', 'http://pnk');

  wordpress-db:
    image: jsurf/rpi-mariadb:latest
    container_name: wordpress-db
    restart: unless-stopped
    networks:
      - wordpress
    volumes:
      - wordpress-db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  unifi:
    image: linuxserver/unifi-controller:arm32v7-latest
    container_name: unifi
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M
    volumes:
      - unifi_config:/config
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"

  etherpad:
    image: jheretic/etherpad:latest
    container_name: etherpad
    networks:
      - local
      - etherpad
    ports:
      - "9001:9001"
    restart: unless-stopped

  etherpad-db:
    image: jsurf/rpi-mariadb:latest
    container_name: etherpad-db
    restart: unless-stopped
    networks:
      - etherpad
    volumes:
      - etherpad-db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=etherpad
      - MYSQL_USER=etherpad
      - MYSQL_PASSWORD=etherpad

  hack-chat:
    image: jheretic/hack-chat:latest
    container_name: hack-chat
    restart: unless-stopped
    networks:
      - local
    ports:
      - "8888:8080"
      - "6060:6060"
    environment:
      - WSPROTOCOL="ws://"
      - WSPORT="6060"
      - WSBASEURL=""
      - ADMIN_NAME=pnk
      - PASSWORD=pnk
      - SALT=2dSg4kS

  droppy:
    image: silverwind/armhf-droppy
    container_name: droppy
    restart: unless-stopped
    networks:
      - local
    volumes:
      - /srv/droppy:/config
      - droppy_files:/files
    ports:
      - 8989:8989

networks:
  local:
  wordpress:
    internal: true
  etherpad:
    internal: true

volumes:
  wordpress_data:
  droppy_files:
  wordpress-db_data:
  etherpad-db_data:
  unifi_config:
