version: '3'
services:
  wordpress:
    image: arm32v7/wordpress:5
    container_name: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - local
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - |
        WORDPRESS_CONFIG_EXTRA=
        define('WP_SITE_URL', 'http://pnk');
        define('WP_HOME', 'http://pnk');

  mariadb:
    image: jsurf/rpi-mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    networks:
      - local
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  unifi:
    image: linuxserver/unifi-controller:arm32v7-latest
    container_name: unifi
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M
    volumes:
      - unifi_config:/config
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"

  etherpad:
    image: jheretic/etherpad:latest
    container_name: etherpad
    networks:
      - local
    ports:
      - "9001:9001"
    restart: unless-stopped

  raspchat:
    image: jheretic/raspchat:latest
    container_name: raspchat
    hostname: pnk
    networks:
      - local
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - RC_URL=http://pnk:3030
      - WS_URL=ws://pnk:3030/chat

  filedrop:
    image: jheretic/filedrop:latest
    container_name: filedrop
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - filedrop_port=8989

networks:
  local:

volumes:
  wordpress_data:
  filedrop_files:
  mariadb_data:
  unifi_config:
