version: '3'
services:
  wordpress:
    image: arm64v8/wordpress:5
    ports:
      - "80:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress

  mariadb:
    image: arm64v8/mariadb:10
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  unifi:
    image: ryansch/unifi-rpi:latest
    restart: always
    volumes:
      - unifi_config:/var/lib/unifi
      - unifi_logs:/var/log/unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "6789:6789"
      - "10001:10001/udp"

volumes:
  mariadb_data:
  unifi_config:
  unifi_logs:
