version: '3'
services:
  traefik:
    image: arm32v6/traefik:1.7
    command: 
      - --docker
    restart: always
    networks:
      - local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

        #nginx:
        #  image: arm32v7/nginx:stable
        #  restart: always
        #  volumes:
        #    - /srv/www:/usr/share/nginx/html:ro
        #  environment:
        #    - WORDPRESS_DB_HOST=mariadb:3306
        #    - WORDPRESS_DB_USER=wordpress
        #    - WORDPRESS_DB_PASSWORD=wordpress
        #  labels:
        #    - "traefik.backend=nginx"
        #    - "traefik.frontend.rule=Host:{{ PNK_HOST }}"

  wordpress:
    image: arm32v7/wordpress:5
    restart: always
    networks:
      - local
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - |
        WORDPRESS_CONFIG_EXTRA=
        define('WP_SITE_URL', 'http://pnk');
        define('WP_HOME', 'http://pnk');
    labels:
      - "traefik.backend=wordpress"
      - "traefik.frontend.rule=Host:{{ PNK_HOST }}"

  mariadb:
    image: jsurf/rpi-mariadb:latest
    restart: always
    networks:
      - local
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  unifi:
    image: ryansch/unifi-rpi:5.11.26-arm32v7
    restart: always
    networks:
      - local
    volumes:
      - unifi_config:/var/lib/unifi
      - unifi_logs:/var/log/unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "6789:6789"
      - "10001:10001/udp"

networks:
  local:

volumes:
  mariadb_data:
  unifi_config:
  unifi_logs:
