version: '3'
services:
  traefik:
    image: arm32v6/traefik:1.7
    container_name: traefik
    command: 
      - --docker
    restart: unless-stopped
    networks:
      - local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wordpress:
    image: arm32v7/wordpress:5
    container_name: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - local
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - |
        WORDPRESS_CONFIG_EXTRA=
        define('WP_SITE_URL', 'http://pnk');
        define('WP_HOME', 'http://pnk');
    labels:
      - "traefik.backend=wordpress"
      - "traefik.frontend.rule=Host:{{ PNK_HOST }}"

  wordpress-cli:
    image: arm32v7/wordpress:cli
    container_name: wordpress-cli
    depends_on:
      - wordpress
      - mariadb
    restart: "no"
    networks:
      - local
    volumes:
      - wordpress_data:/var/www/html
      - /srv/wordpress:/files
    command: >
      /bin/sh -c '
      wp core is-installed || {
        wp core install --url=pnk --title=PNK --admin_user=pnk --admin_password=pnk --admin_email=contact@pnkgo.com --skip-email
        wp plugin install /files/wordpress-importer.zip
        wp import /files/portablenetworkkitpnk.WordPress.2019-08-14.xml --authors=create
      }'

  mariadb:
    image: jsurf/rpi-mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    networks:
      - local
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  unifi:
    image: linuxserver/unifi-controller:arm32v7-latest
    container_name: unifi
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M
    volumes:
      - unifi_config:/config
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"

  ngircd:
    image: linuxserver/ngircd:arm32v7-latest
    container_name: ngircd
    networks:
      - local
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/ngircd:/config
    restart: unless-stopped

  thelounge:
    image: linuxserver/thelounge:arm32v7-latest
    container_name: thelounge
    networks:
      - local
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/thelounge:/config
    restart: unless-stopped
    ports:
      - "9000:9000"
    labels:
      - "traefik.backend=thelounge"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:{{ PNK_HOST }};PathPrefix:/chat/"
      - "traefik.frontend.redirect.regex=^(.*)/chat$$"
      - "traefik.frontend.redirect.replacement=$$1/chat/"
      - "traefik.frontend.rule=PathPrefix:/chat;ReplacePathRegex: ^/chat/(.*) /$$1"
  
  droppy:
    image: silverwind/armhf-droppy
    container_name: droppy
    restart: unless-stopped
    volumes:
      - /srv/droppy:/config
      - droppy_files:/files
    ports:
      - 8989:8989
    labels:
      - "traefik.backend=droppy"
      - "traefik.port=8989"
      - "traefik.frontend.rule=Host:{{ PNK_HOST }};PathPrefix:/fileshare"
      - "traefik.frontend.redirect.regex=^(.*)/fileshare$$"
      - "traefik.frontend.redirect.replacement=$$1/fileshare/"
      - "traefik.frontend.rule=PathPrefix:/fileshare;ReplacePathRegex: ^/fileshare/(.*) /$$1"

networks:
  local:

volumes:
  wordpress_data:
  droppy_files:
  mariadb_data:
  unifi_config:
