version: '3'
services:
  traefik:
    image: arm32v6/traefik:2.0
    restart: always
    volumes:
      - /etc/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: arm32v7/nginx:stable
    restart: always
    volumes:
      - /srv/http:/usr/share/nginx/html:ro
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress

  wordpress:
    image: arm32v7/wordpress:5
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress

  mariadb:
    image: jsurf/rpi-mariadb:latest
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  unifi:
    image: ryansch/unifi-rpi:5.11.26-arm32v7
    restart: always
    volumes:
      - unifi_config:/var/lib/unifi
      - unifi_logs:/var/log/unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "6789:6789"
      - "10001:10001/udp"

volumes:
  mariadb_data:
  unifi_config:
  unifi_logs:
